version: '3.8'
services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: account_db
      DB_DATABASE: accountService
      DB_USERNAME: root
      DB_PASSWORD: root
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - account_db

  account_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: accountService
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33070:3306
